### PR TITLE
Setup Tailwind CSS for the column block

### PR DESCRIPTION
**Pull request by JustinyAhin**
# Summary

This PR adds Tailwind CSS as a Post CSS plugin (see https://tailwindcss.com/docs/installation/using-postcss). 

The Tailwind configuration is the default one in Yoast admin ui toolkit (https://github.com/Yoast/admin-ui/blob/trunk/packages/toolkit/configs/tailwind.js) with a few changes.

In package.json, two new commands are added `build:tailwind` and `watch:tailwind` that scan all the JavaScript files in the `/src` folder and generate CSS code based on the Tailwind utilities used in these files.

`build:tailwind` outputs a minified and production optimized `style.min.css` file in the `/build` folder. 

`watch:tailwind` watch the `/src` folder for any change, outputs and updates a `style.css` file in the `/build` folder.

# How to test
- After running `npm install`, add a Tailwind utility class to one of the JavaScript file in `/src`. For example, update https://github.com/Yoast/yoast-tailwind-columns-block/blob/c18c9adca114d926d2b7e7b73017de53751512ab/column/src/edit.js#L103-L105 to:

```
<div { ...blockProps } class="yst-bg-indigo-100">
    <InnerBlocks />
</div>
```
- Run `npm run build:tailwind` 

There should be a new `style.min.css` file in the build folder.

### CODE REVIEW

**Comment by aristath** [comment]
@JustinyAhin Is there a way for tailwind to just generate the CSS without looking at the JS files?
Most of the classes we will be adding, will be dynamically-generated, and from what I understand tailwind won't be able to detect those in the JS files. So unless we explicitly add `col-span-4`, `col-start-7` and so on (~30 classes minimum), it won't generate any CSS for those.
Also, for the columns blocks we won't need colors etc, we only want the layout styles 🤔

**Comment by JustinyAhin** [comment]
@aristath Tailwind allows classes safelisting (https://tailwindcss.com/docs/content-configuration#safelisting-classes) in its configuration.

I think this might be the best approach.

**Comment by JustinyAhin** [comment]
> @aristath Tailwind allows classes safelisting (https://tailwindcss.com/docs/content-configuration#safelisting-classes) in its configuration.
> 
> I think this might be the best approach.

Doing this will make all the safe listed classes styles to be included per default in the generated CSS file.

**Comment by aristath** [comment]
Hmmm I added this in `tailwind.config.js`, but I still don't see a stylesheet compiled. What am I doing wrong? Do you get a stylesheet compiled? 🤔 
```
	safelist: [
		'yst-col-start-1',
		'yst-col-start-2',
		'yst-col-start-3',
		'yst-col-start-4',
		'yst-col-start-5',
		'yst-col-start-6',
		'yst-col-start-7',
		'yst-col-start-8',
		'yst-col-start-9',
		'yst-col-start-10',
		'yst-col-start-11',
		'yst-col-start-12',
		'yst-col-span-1',
		'yst-col-span-2',
		'yst-col-span-3',
		'yst-col-span-4',
		'yst-col-span-5',
		'yst-col-span-6',
		'yst-col-span-7',
		'yst-col-span-8',
		'yst-col-span-9',
		'yst-col-span-10',
		'yst-col-span-11',
		'yst-col-span-12',
		'yst-col-end-1',
		'yst-col-end-2',
		'yst-col-end-3',
		'yst-col-end-4',
		'yst-col-end-5',
		'yst-col-end-6',
		'yst-col-end-7',
		'yst-col-end-8',
		'yst-col-end-9',
		'yst-col-end-10',
		'yst-col-end-11',
		'yst-col-end-12',
		'yst-col-end-13',
	],
```

**Comment by JustinyAhin** [comment]
🤔 it does works for me @aristath. Yes I get the compiled stylesheet.

**Comment by JustinyAhin** [comment]
@aristath you can see the stylesheets in this commit https://github.com/Yoast/yoast-tailwind-columns-block/pull/2/commits/2732d608bad52801a9f893ea000f9d08ebac0c1c.



We will probably maintain the safe list in another file, this commit is just for demonstration.

**Comment by carolinan** [comment]
The tailwind docs mention 
"If you’re authoring content in a format that compiles to HTML (like Markdown), it often makes sense to compile that content to HTML before scanning it for class name"
https://tailwindcss.com/docs/content-configuration#transforming-source-files

But how to we make it scan the block classes after they are generated?
I mean there are many ways to output the block markup.

**Comment by aristath** [comment]
I don't think that's something we can do @carolinan...
We're simply going to have to add styles for all classes we need, instead of doing it on-render. At least in the beginning, that's what we'll have to do. We need to get something functional before going over optimizations in the build processes etc 👍

**Comment by aristath** [comment]
I made a couple of tweaks just to get the ball rolling and I'll go ahead and merge this.
We can tweak and refine as we go 👍

**Comment by JustinyAhin** [comment]
@aristath do we want to include the non-minified CSS in the build?

**Comment by aristath** [comment]
Yeah, let's leave it for now... I'm sure we'll want to remove it in the future, but for now it'll make debugging a bit easier 👍

**Pull request merged**
